config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout",
                                   sign_up: "register" }
  resources :products
  root "products#index"

  resources :charges, only: [:new, :create]

  get "/cart"       => "carts#index"
  get "/cart/clear" => "carts#clear_cart"
  get "/cart/:id"   => "carts#add"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# app/models/product.rb
class Product < ApplicationRecord
  has_many :variations, dependent: :destroy
  accepts_nested_attributes_for :variations, allow_destroy: true

  mount_uploaders :pictures, PictureUploader
  paginates_per 12

  monetize :price_cents

  before_save { self.price_cents = price_cents.to_i }

  validates :title,       presence: true, length: { maximum: 32 }
  validates :maker,       presence: true, length: { maximum: 20 }
  validates :description, presence: true
  validates :price_cents, presence: true,
                          numericality: { greater_than_or_equal_to: 0,
                                          only_integer: true }
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/variation.rb
# app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :product

  before_save { self.quantity = quantity.to_i }

  scope :unique_by_size,  -> { select(:size).uniq  }
  scope :unique_by_color, -> { select(:color).uniq }

  # Accepts only 3XS XXS XS S M L XL XXL 3XL
  VALID_SIZE_REGEX = /\A[3X]?[X]?((?<!3)[SL]|(?<!\w)[M])\z/
  validates :size,     presence: true, length: { maximum: 3 },
                       format: { with: VALID_SIZE_REGEX }
  validates :color,    presence: true, length: { maximum: 20 }
  validates :quantity, presence: true,
                       numericality: { greater_than_or_equal_to: 0 }
  # First three characters are letters with exception of I, L and O,
  # next three characters are digits
  VALID_ITEM_NUMBER_REGEX = /\A[A-HJKMNP-Z]{3}\d{3}\z/
  validates :item_number, presence: true, length: { maximum: 6 },
                          format: { with: VALID_ITEM_NUMBER_REGEX },
                          uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
# app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    # If there is a cart, display it. Otherwise, pass an empty value.
    return @cart = session[:cart] if session[:cart]
    @cart = {}
  end

  def add
    id = params[:id]
    # Create a new cart, if a cart is not already created.
    session[:cart] ||= {}
    cart = session[:cart]

    # If a product is already in the cart, increment the quantity value.
    cart[id] ||= 0
    cart[id] += 1
    redirect_to cart_path
  end

  def clear_cart
    session[:cart] = nil
    redirect_to action: :index
  end
end

app/controllers/charges_controller.rb
# app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = params[:stripeAmount]
    @email  = params[:stripeEmail]
    @card   = params[:stripeToken]

    begin
      @amount = @amount.to_i # Must be an integer!
    rescue
      flash[:error] = "Charge not completed. Please enter a valid amount."
      redirect_to cart_path
      return
    end

    customer = Stripe::Customer.create(
      email: @email,
      card: @card
    )

    Stripe::Charge.create(
      amount: @amount,
      currency: "aud",
      customer: customer.id,
      receipt_email: @email,
      description: "Charge for #{@email}"
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
    flash[:notice] = "Please try again!"
  end
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :admin_user, except: [:index, :show]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.order(:title).page params[:page]
  end

  def show
  end

  def new
    @product = Product.new
    @product.variations.build
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render "edit"
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

    def product_params
      params.require(:product).permit(:title, :maker, :price, :description,
                                      pictures: [],
                                      variations_attributes:
                                        [:item_number, :size, :color,
                                         :quantity, :_destroy, :id])
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def admin_user
      redirect_to root_path unless user_signed_in? && current_user.try(:admin?)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
  <p>Your cart is empty.</p>
<% else %>
  <p><%= link_to "Empty Your Cart", cart_clear_path %></p>
<% end %>
<br><br>

<% total = 0 %>

<ul>
<%= @cart %>
<% @cart.each do |id, quantity| %>
  <% product = Product.find_by_id(id) %>
  <li>
    <%= link_to product.title, product %>
    <p><%= product.description %></p>
    <p><%= humanized_money_with_symbol(product.price) %></p>
    <p>Quantity: <%= quantity %></p>
  </li>
  <% total += quantity * product.price %>
<% end %>
<p><b>Total: <%= humanized_money_with_symbol(total) %></b></p>
</ul>
<% provide(:amount_to_pay, "#{(total * 100).to_i}") %>
<%= render "/charges/new" %>

app/views/charges/_new.html.erb
<%= form_tag charges_path, id: "stripeForm" do %>
  <article>
    <%= hidden_field_tag :stripeToken %>
    <%= hidden_field_tag :stripeEmail %>
    <%= hidden_field_tag :stripeAmount %>
  </article>
  <button id="stripe-button">Purchase</button>
<% end %>

<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
  var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    locale: "auto",
    name: "T-Shirt Store",
    description: "Thank you for the purchase!",
    token: function(token) {
      $("input#stripeToken").val(token.id);
      $("input#stripeEmail").val(token.email);
      $("input#stripeAmount").val(<%= yield :amount_to_pay %>);
      $("#stripeForm").submit();
    }
  });

  $("#stripe-button").on("click", function(e) {
    var amount = <%= yield :amount_to_pay %>;
    amount = parseInt(amount);
    handler.open({
      amount: amount,
      email: "<%= current_user.email %>",
      billingAddress: true,
      shippingAddress: true,
      allowRememberMe: true
    })
    e.preventDefault();
  });

  // Close Checkout on page navigation
  $(window).on("popstate", function() {
    handler.close();
  });
</script>

app/views/charges/create.html.erb
<h2>Thank you!</h2>
<p>Your payment of <strong><%=number_to_currency(@amount * 0.01) %></strong>
 has been received.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T-Shirt Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "T-Shirt Store", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && current_user.try(:admin?) %>
          <li><%= link_to "Add Product", new_product_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/products/_carousel.html.erb
<div id="pictureCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  <% @product.pictures_urls.each_index do |picture_index| %>
    <li data-target="#pictureCarousel" data-slide-to="<%= picture_index %>"<%= " class=\"active\"".html_safe if picture_index == 0 %>></li>
  <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  <% if @product.pictures_urls and !@product.pictures_urls.empty? %>
    <% @product.pictures_urls.each do |picture| %>
    <div class="item<%= " active" if @product.pictures_urls.index(picture) == 0 && picture %>">
      <%= image_tag(picture, class: "img-responsive", width: "100%", alt: @product.title) if picture %>
    </div>
    <% end %>
  <% else %>
    <div>
      <img src=<%= yield :picture_placeholder %> class="img-responsive img-rounded">
    </div>
  <% end %>
  </div>

  <% if @product.pictures_urls and !@product.pictures_urls.empty? %>
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#pictureCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#pictureCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product, html: { multipart: true } do |f| %>
  <%= f.input  :title, label: "Product Title" %>
  <%= f.input  :maker %>
  <%= f.input  :price %>
  <%= f.input  :description %>
  <%= f.file_field :pictures, multiple: true %>
  <div class="container-fluid">
    <div class="row">
    <%= f.nested_fields_for :variations do |v| %>
        <div class="col-xs-3"><%= v.input :item_number %></div>
        <div class="col-xs-2"><%= v.input :size %></div>
        <div class="col-xs-2"><%= v.input :color %></div>
        <div class="col-xs-2"><%= v.input :quantity %></div>
        <div class="col-xs-3">
        <%= v.remove_nested_fields_link "Remove", class: "btn btn-danger",
          role: "button", data: { confirm: 'Are you sure?' } %>
        </div>
    <% end %>
    </div>
  <%= f.add_nested_fields_link :variations, "Add a row",
    class: "btn btn-primary", role: "button" %>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="container-fluid index-center">
  <%= paginate @products, theme: "bootstrap" %>
  <div class="row">
    <% @products.each do |product| %>
    <% if product %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="image-wrapper overlay-fade-in">

        <% picture = product.pictures_urls.sample %>
        <%= image_tag(picture, class: "img-responsive", width: "100%",
                               alt: product.title) if picture%>

        <div class="image-overlay-content">
          <h2><%= product.title %></h2>
          <p><%= humanized_money_with_symbol(product.price) %></p>
          <%= link_to "Show", product_path(product), class: "button" %>
          <% if user_signed_in? %>
          <%= link_to "Add to Cart", "/cart/#{product.id}", class: "button" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <%= paginate @products, theme: "bootstrap"  %>
</div>

app/views/products/new.html.erb
<h1>New T-Shirt</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="col-xs-12 col-md-6">
    <% provide(:picture_placeholder,
               "http://placehold.it/700x700?text=Sorry...+no+picture+:-(") %>
    <%= render partial: "carousel" %>
    <%= link_to "Back", root_path %>
    <% if user_signed_in? && current_user.try(:admin?) %>
      <%= link_to "Edit", edit_product_path(@product) %>
      <%= link_to "Delete", product_path(@product), method: :delete,
                                                  data: { confirm: "Are you sure?" } %>
    <% end %>

  </div>
  <div class="col-xs-12 col-md-6">
    <h2><%= @product.title %></h2>
    <h4><%= @product.maker %></h4>
    <h2><%= humanized_money_with_symbol(@product.price) %></h2>
    <p><%= @product.description %></p>
    <p>
      <%= collection_select :variation, "color", @product.variations.unique_by_color, :id, :color, include_blank: false, prompt: true, class: "form-control" %>
    </p>
    <p>
      <%= collection_select :variation, "size", @product.variations.unique_by_size, :id, :size, include_blank: false, prompt: true, class: "form-control" %>
    </p>
    <button class="btn btn-default" id="color_chosen"></button>
    <button class="btn btn-default" id="size_chosen"></button>
  </div>
</div>